name: Sync Fork
on:
  schedule:
    - cron: "00 20 * * *"
  workflow_dispatch:
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
jobs:
  sync:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - remoteOwner: "XTLS"
            remoteName: "Xray-core"
          - remoteOwner: "v2fly"
            remoteName: "v2ray-core"
    steps:
      - name: Set up Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global advice.detachedHead false
      - name: Sync ${{ matrix.remoteName }}
        run: |
          remote_branch="$(curl -sL https://api.github.com/repos/${{ matrix.remoteOwner }}/${{ matrix.remoteName }} | jq -r '.default_branch')"
          git clone https://github.com/${{ github.repository_owner }}/${{ matrix.remoteName }}.git
          cd ${{ matrix.remoteName }}
          git remote add upstream https://github.com/${{ matrix.remoteOwner }}/${{ matrix.remoteName }}.git
          git fetch upstream
          git reset --hard upstream/$remote_branch
          git push origin $remote_branch --force
