name: Sync Fork
on:
  schedule:
    - cron: "00 20 * * *"
  workflow_dispatch:
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Git config
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global advice.detachedHead false
      - name: Sync Xray-core
        run: |
          remote_branch="$(curl -sL https://api.github.com/repos/XTLS/Xray-core/releases/latest | jq -r '.default_branch')"
          git clone https://github.com/maoxikun/Xray-core.git
          git remote add upstream https://github.com/XTLS/Xray-core.git
          git fetch upstream
          git reset --hard upstream/$remote_branch
          git push origin $remote_branch --force
      - name: Sync v2ray-core
        run: |
          remote_branch="$(curl -sL https://api.github.com/repos/v2fly/v2ray-core/releases/latest | jq -r '.default_branch')"
          git clone https://github.com/maoxikun/v2ray-core.git
          git remote add upstream https://github.com/v2fly/v2ray-core.git
          git fetch upstream
          git reset --hard upstream/$remote_branch
          git push origin $remote_branch --force
